### ISSUE TITLE
Terminal escape sequence in logs

### ISSUE THREAD

**Issue by LeForjeron** [kiss-community/kiss#10]
When using build tools such as ninja, terminal escape sequence for output colorizing are printed in the log file.

**Comment by cemkeylan** [comment]
This is not a package manager issue. The package manager pipes all output to the log file. Some tools disable colours when they understand that their output is being piped, but some does not.

Only way to disable escape sequences is by using a stream editor, which is an expensive operation and we don't want that.

You can instead use `less -R` for previewing log files, which removes (on busybox) or preview (GNU less) those colour escapes.

**Comment by dilyn-corner** [comment]
The 'solution' is to probably disable `KISS_COLOR` for these packages if one doesn't wish to use a pager, no?

**Comment by cemkeylan** [comment]
@dilyn-corner Setting `KISS_COLOR` only disables the colour of package manager messages, which aren't part of the build output.

**Comment by dilyn-corner** [comment]
Ah, I am a dumb. Ignore me.

**Comment by cemkeylan** [comment]
It's alright, the documentation is a bit vague :P
