### ISSUE TITLE
please as a valid KISS_SU

### ISSUE THREAD

**Issue by cjwyett** [kiss-community/kiss#12]
Can we please have [please](https://github.com/edneville/please) as a KISS_SU option.

**Comment by dilyn-corner** [comment]
We could have it if `please` were packaged; otherwise, you can use a patch like this...

```
diff --git a/kiss b/kiss
index a49886f..b06d0be 100755
--- a/kiss
+++ b/kiss
@@ -46,7 +46,7 @@ as_root() {
         ;;
 
         *)
-            die "Invalid KISS_SU value: ${su##*/} (valid: doas, sudo, ssu, su)"
+            die "Invalid KISS_SU value: ${su##*/} (valid: doas, please, sudo, ssu, su)"
         ;;
     esac
 }
@@ -1632,7 +1632,11 @@ main() {
 
     # Figure out which 'sudo' command to use based on the user's choice or what
     # is available on the system.
-    su=${KISS_SU:-"$(command -v sudo || command -v doas || command -v ssu)"} || su=su
+    su=${KISS_SU:-"$(command -v sudo   || 
+                     command -v doas   || 
+                     command -v ssu    ||
+                     command -v please
+    )"} || su=su
 
     # Figure out which utility is available to dump elf information.
     elf_cmd=${KISS_ELF:="$(
```

**Comment by cjwyett** [comment]
Brilliant, thanks!

**Comment by cemkeylan** [comment]
The patch above does not add please to accepted options, but this should work: https://gist.github.com/6c280ac11fd3844001c59a0f86568e94

**Comment by dilyn-corner** [comment]
I knew I was missing one...

**Comment by cemkeylan** [comment]
By the way, I don't see any issues with adding this patch to mainline even if it isn't packaged at community. The syntax seems no different than sudo, doas, or ssu. This just adds an extra `command -v` call, which is a pretty cheap operation.

**Comment by dilyn-corner** [comment]
You're right, but my concern is that we establish a precedent where any given privilege escalation tool gets added to the list of allowable tools and isn't part of the ecosystem. FWIW, I'm far more inclined to simply allow KISS_SU to *define* the implementation if it is set, that way users can use `please` et al., not have the 'responsibilty' of maintaining it, and every `tom`, `dick`, and `harry' doesn't get requested for support...

**Comment by cemkeylan** [comment]
So, something like "use doas, sudo, ssu if KISS_SU is not set, use whatever is given if it is set?"
