### ISSUE TITLE
dependency detector broken with ksh (readelf)

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/kiss#15]
KISS's dependency detector doesn't seem to work when using `ksh`, because of different output when parsing the lines.

`line="0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]`

Around [this](https://github.com/kiss-community/kiss/blob/master/kiss#L468) line, KISS parses the output like so:

`ash`:
```
-> echo ${line##*[}
libz.so.1]
```

`ksh`:
```
-> echo ${line##*[}
0x0000000000000001 (NEEDED) Shared library: [libz.so.1]
```

**Comment by aaronNGi** [comment]
echo ${line##*\[}

Escaping the '[' should fix it. I guess `ash` is just trying to be smart and not treat an opening bracket as character class/range, when there's nothing following it. I feel like escaping it, when we want a literal '[', is the right thing to do anyway.

**Comment by dilyn-corner** [comment]
That was my first thought. @git-bruh, if you'd be kind enough to give it a quick try
