### ISSUE TITLE
Issue with shallow cloning

### ISSUE THREAD

**Issue by LeForjeron** [kiss-community/kiss#18]
When using git to pull retrieve package source, kiss uses shallow cloning to avoid downloading the entire git repo.
Some package use `git describe --tags` to generate their versioning, but that command fail with "No names found, cannot describe anything." on shallow clones.
Even the --tags option kiss uses is not enough for the describe command to complete.
Maybe we should add a option to disable shallow cloning ?
It might be unecessary since one can always use `git fetch --unshallow` in the build file, but we should at least add a section in the documentation.

**Comment by dilyn-corner** [comment]
I can document this behavior (I think the only mention of shallow cloning by `kiss` is in a single blog post), if adding an option to disable it can be done cleanly, maybe; but I think if the number of packages that *require* an unshallow clone is <<<< unaffected packages, building it into the build file is probably the better route - the only way `kiss` would know there's a problem is after the clone has been made, and setting a var specifically for that package when building means that every package built along with will also inherit the behavior. Not the worst, just defeats the point.

Would you happen to have examples of packages that have this problem?

**Comment by LeForjeron** [comment]
I stumbled across this issue while trying to build nextpnr (a place and route software for FPGA development). People had the issue with others build system here : https://stackoverflow.com/questions/4916492/git-describe-fails-with-fatal-no-names-found-cannot-describe-anything

**Comment by dilyn-corner** [comment]
Sorry for the delay! I've documented this behavior here: https://github.com/kiss-community/website/commit/adc1226b2cf62ed8ea43dd4c4735b2e4deadabf1
We also had a discussion about what to do with this more broadly here https://github.com/kiss-community/website/pull/3

As a further note: if this issue starts to impact larger percentages of packages, we can look at changing the default behavior (I think it would essentially amount to reverting https://github.com/kiss-community/kiss/commit/c1bdf283f2f7ae6bd4c5d8338605b75b20b3fd67
