### ISSUE TITLE
When a build fails kiss logs the path of the log file with an extra slash

### ISSUE THREAD

**Issue by AndreiSva** [kiss-community/kiss#33]
Example: 
![test](https://user-images.githubusercontent.com/51296839/121740494-031aa780-cab2-11eb-8970-c027e1b552da.png)

Is this intended behavior?

**Comment by git-bruh** [comment]
> `log "$pkg" "Log stored to $log_dir/$pkg-$time-$pid"`

KISS can store logs in the path specified in the `log_dir` environment variable so if you set it to a path without a trailing slash like `log_dir=/tmp`,  KISS would try to store the log in `/tmptest-...` instead of `/tmp/test...` so `$log_dir/...` prevents failure in such cases.

**Comment by AndreiSva** [comment]
it appears `log_dir` has a trailing slash by default then? I didn't specify a custom log directory and this happens :/

**Comment by git-bruh** [comment]
The extra slash is there to ensure that the path doesn't get messed up in case the path doesn't have a trailing slash so you get double slashes with the default path

**Comment by illiliti** [comment]
Extra slash is harmless. Please close the issue.

**Comment by AndreiSva** [comment]
alright
