### ISSUE TITLE
Fix random dependency issue

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/kiss#5]
https://github.com/kiss-community/repo-main/issues/18
https://github.com/kisslinux/kiss/issues/194

`kiss` sometimes skips a few dependencies when building a package.

**Comment by dilyn-corner** [comment]
For this interested in helping with debugging this, you can opt to use this as a starter when doing builds and updates:
`sh -x <path to kiss> <args> >file 2>&1`

Tag E5ten, myself, others if you want, with the logs in IRC or paste them here!

Might I suggest someone be adventurous and try this repeatedly with a package that requires multiple packages be installed, one of which being `meson`? I have a hunch

**Comment by git-bruh** [comment]
To repro:

* 4 packages:
`foo`: Test package that depends on `bar` and `baz`. (`build` file like `cc test.c -lbar -lbaz`)
`qux`: Common dependency for `bar` and `baz`

If you try to build `foo` the first time, it'll work fine.

If you remove `bar`, `baz` and `qux`, and also remove the cached binary `~/.cache/kiss/bin/qux@1-1.tar.gz` and then try to build `bar`, KISS  will skip the installation of `qux`, hence breaking `bar` and `baz`.

An example of this in KISS repos:

`foo=testpkg`
`bar=atk`
`baz=glib`
`qux=libffi`

https://0x0.st/-TEz.txt, here the cached binaries for `atk` and `glib` are present, but not for `libffi`. KISS skips `libffi`, installs `atk` AND `glib` and then starts rebuilding atk!

**Comment by git-bruh** [comment]
Logs:
* [Pass (`bar`, `baz`, `qaz` installed)](https://0x0.st/-TIH.txt)
* [Fail (`qaz` installation skipped)](https://0x0.st/-TIX.txt)

Note that this isn't the exact same issue as the others (where a dependency is skipped on the first time of building a package), but i feel that both these issues stem from the same bug in the code.

**Comment by aaronNGi** [comment]
Good job figuring out the steps to reproduce. Following those steps, I made myself 4 test packages with empty build files. Eventually managed to figure out the problem. See the dev mailing list for a patch and detailed explanation of what caused this bug.

**Comment by sdsddsd1** [comment]
I felt the development on the ML and posted patch is missing here.
https://archive.k1sslinux.org/dev/thread/ebb3eb33b9e9e17c9c2df05a08890074%40disroot.org.html

**Comment by dilyn-corner** [comment]
I've updated the cronjob to update the list more regularly. 

If it sees higher volume, I'll probably change it to 'update as mails roll in'. But I'd rather keep the overhead low for now :)

Was merged. Thanks all <3
