### ISSUE TITLE
RFC: "alternate" sources

### ISSUE THREAD

**Issue by dantehaversham** [kiss-community/kiss#7]
gnu.org was down for a few hours the other day which made me think it would be useful if there was a feature in which if a "primary" source timesout or is down it switches to an alternative source. i'm not sure how this could look like but i think it would be good to start a discussion about this. possibly something like:

```
https://ftp.gnu.org/gnu/make/make-4.3.tar.gz
https://anotherwebsite.com/make-4.3.tar.gz
```
and if the name of the file is the same, in this case `make-4.3.tar.gz`, then it treats the sources as alternates. but i'm sure someone can think of a better way.

**Comment by kyx0r** [comment]
If the primary source is down you can just go into sources file for that package and change the url, when updating the system kiss uses git pull which will not discard your local changes. I don't think this is necessary, kiss is feature complete.

**Comment by kyx0r** [comment]
The scenario of having primary source down is pretty rare, especially if the packages are well maintained and updated regularly.

**Comment by dilyn-corner** [comment]
Modifying git repositories and not at least commiting those changes will result in `kiss` being unable to continue with a `kiss u`, so modifying sources temporarily would result in some additional user intervention. 

It's an interesting idea but I'm not certain truly useful it would be; it sounds like kicking the can down the road more than solving a problem we can't control. If GitHub goes down hard enough, for instance, lots of repo and community packages are harder to get. But where else are many of these packages mirrored to?
