### ISSUE TITLE
kiss-chroot: mount some more paths

### ISSUE THREAD

**Issue by git-bruh** [kiss-community/kiss#8]
It would be nice to have a few extra paths mounted by `kiss-chroot`:
* `/dev/shm`: `python` multiprocessing breaks, which in turn breaks building `firefox` and probably `chromium` too which can be pretty annoying (requires a full rebuild of `python`, maybe a check should be added to the build file aswell ?).
* `/tmp`, `/run`: not really necessary, but helps keep the directories clean.

**Comment by dilyn-corner** [comment]
Not mounting `/dev/shm` doesn't break `firefox` builds for me - indeed `/dev/shm` exists in my chroot just fine. On Debian you might have an issue with `shm` because `/dev/shm -> /run/shm`, but that's not how (default) KISS does it. 

Uncertain about `/tmp` and `/run` being necessary - uncertain what benefits it would confer.

**Comment by git-bruh** [comment]
If you compile python without `/dev/shm` mounted, it fails to detect some multiprocessing stuff because the normal user won't have access to an unmounted `/dev/shm`, then if you try `import multiprocessing.synchronize` in `python` it will fail. Hence ff build breaks.

**Comment by dilyn-corner** [comment]
Unless I did something fancy when I wasn't looking, I never mounted `/dev/shm` and did `kiss b firefox` from a completely fresh chroot yesterday and had no issues. Interesting.

**Comment by git-bruh** [comment]
No, it will fail only if `python` is compiled with an unmounted `/dev/shm`. If `python` was built properly then you wont have issues

**Comment by dilyn-corner** [comment]
I'm saying the python I would've used was built without a mounted shm, unless I'm actually just very confused.

**Comment by git-bruh** [comment]
Did you build it as root ? Because then your user would have write access to that path and it would build properly.

**Comment by dilyn-corner** [comment]
You are in fact absolutely right. 

The real question is how often does this actually come up in practice? Is there any effective downside to mounting it? 

Note that no other guide I have ever seen for chrooting mentions this; I think that it's in general a nonissue, although it may be worth documenting somewhere.

**Comment by git-bruh** [comment]
It's mostly a problem when you're starting from a fresh KISS chroot and wonder why your `python` broke (maybe add a check to the `build` file as i said earlier), otherwise the only time it's a problem for me is running some programs like `chromium` which need a `/dev/shm` mounted. Your choice, I can always just modify the script locally :)

**Comment by git-bruh** [comment]
`chromium` build fails even if both `python`s are built properly:

```
ninja: job failed: python ../../build/util/python2_action.py ../../mojo/public/tools/mojom/mojo
77/build/chromium/out/Release/gen --output-root /home/build/trash/1477/build/chromium/out/Relea
default__rule..rsp --check-imports /home/build/trash/1477/build/chromium/out/Release/gen/mojo/p
six --enable-feature is_linux --add-module-metadata webui_module_path=chrome://resources/mojo/m
Traceback (most recent call last):
  File "../../mojo/public/tools/mojom/mojom_parser.py", line 442, in <module>
    Run(sys.argv[1:])
  File "../../mojo/public/tools/mojom/mojom_parser.py", line 434, in Run
    module_metadata, allowed_imports)
  File "../../mojo/public/tools/mojom/mojom_parser.py", line 258, in _ParseMojoms
    for mojom_abspath, ast in _Shard(_ParseAstHelper, map_args):
  File "../../mojo/public/tools/mojom/mojom_parser.py", line 205, in _Shard
    pool = multiprocessing.Pool(processes=processes)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 140, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 236, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied
```

**Comment by dilyn-corner** [comment]
I don't W A N N A

**Comment by git-bruh** [comment]
Was just adding another example to `The real question is how often does this actually come up in practice?`
