### ISSUE TITLE
?no-extract suffix confusion

### ISSUE THREAD

**Issue by mmatongo** [kiss-community/kiss#9]
Coming up on some luck with my attempts to port Java to kiss I've encountered a very mundane problem.

So in order for me to compile Java I need to download some packages that are meant to be used during the build process.

Now I need to not have this files extracted but at the same time I need them to not have the suffix because they aren't recognised if they have it.

@dilyn-corner Help

**Comment by dilyn-corner** [comment]
You can just move them in the build script :) See how `rust` [does it](https://github.com/kiss-community/repo-main/blob/master/extra/rust/build)

**Comment by mmatongo** [comment]
Tried this and what I get is mv: can't rename ```sh *.tar.xz?no-extract': No such file or directory```

**Comment by mmatongo** [comment]
Never-mind, my lack of sleep was impairing my judgement I couldn't see the `xz` for some reason.

**Comment by dilyn-corner** [comment]
Happens to the best of us. Let me know if you need any help getting `java` to work! Would love to see this succeed.

**Comment by mmatongo** [comment]
I could use some help

Please take a look here https://github.com/mmatongo/kiss-lang/tree/openjdk7-jre/testing/java/openjdk7-jre
